spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task
    username: postgres
    password: ARTEM565
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect